allprojects {
    version = project.mod_version
    group = project.maven_group
}

subprojects {
    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}