plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

base {
    archivesName = "${archives_base_name}-common"
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "signeditgui" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    // Only compile against the loader, not the full Fabric API
    compileOnly "net.fabricmc:fabric-loader:${loader_version}"
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from("${rootProject.projectDir}/LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}
